# Tensorfow Baise syntex

In [2]:
import tensorflow as tf # Import tensorflow in notebook

In [3]:
intvar = tf.constant(2) # Create a int type(numpy.int32) constant variable
floatvar = tf.constant(2.1) # Create a float type(numpy.float32) constant variable
stringvar = tf.constant("hello world") # Create a bytes type constant variable

In [4]:
print(tf.__version__) # check version of tensorflow

1.2.1


In [5]:
# method 1st to run the tensorflow Session() to print output
with tf.Session() as sess:
    res = sess.run(stringvar)

#method 2nd 
sess = tf.Session()
result = sess.run(intvar)

# Matrix Baise

In [6]:
# Different types of matrix in  tensorflow

fill_mat = tf.fill((4,4),10)                              # IN this matrix all values 10

zeros = tf.zeros((4,4))                                   # In this matrix all values 0

ones = tf.ones((4,4))                                     # In this matrix all values 0

randn = tf.random_normal((4,4),mean = 0, stddev = 1.0)    # In this random value matrix

randu = tf.random_uniform((4,4),minval =0, maxval = 1)    # In this matrix all value present in 0 to 1

all_matrix = [fill_mat,zeros,ones,randn,randu]            # print all matrix in one line so we create a list

sess = tf.InteractiveSession()                            # Instant use or upper method we use these method also 
                                                          # after tf.InteractiveSession() we do not need to again call the tf.Session() method/tf.InteractiveSession() 
#print(sess.run(all_matrix))                              # print all matrix 
for mat in all_matrix:                                
    print(mat.eval())                                       # Instant use or run method we use also eval method
    print("----------")
    


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
----------
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
----------
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
----------
[[ 2.6778512  -0.44950441  0.68417555  1.26591134]
 [ 1.38298738  0.91143453 -0.87885958  0.58612567]
 [-1.01340556 -1.32137692 -0.13778155  0.55875647]
 [-0.51854008  0.90628374 -0.73594421  1.8770721 ]]
----------
[[ 0.72965527  0.63948619  0.72459447  0.52562475]
 [ 0.23425448  0.55610836  0.54483056  0.92356539]
 [ 0.69068801  0.25771725  0.44675958  0.79752922]
 [ 0.13443434  0.32279444  0.2893002   0.80869389]]
----------


In [7]:
print(fill_mat.get_shape)        # To check matrix shape

result = tf.matmul(zeros,ones)   # matiply t o matrix but float type or int matrix not matiply togather
sess.run(result)

<bound method Tensor.get_shape of <tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>>


array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]], dtype=float32)

# TF Graphs

In [8]:
g = tf.get_default_graph()

In [9]:
print(g)

In [10]:
g1 = tf.Graph()

In [11]:
print(g1)

#  placeholder and variable Initializer


In [12]:
mat = tf.random_uniform((4,4),0,1) # Create matrix

In [13]:
var = tf.Variable(initial_value = 4) # Create variable and initialize vlue is 4

In [14]:
print(var) 

<tf.Variable 'Variable:0' shape=() dtype=int32_ref>


In [24]:
#sess.run(var) # 

# Error
sess.run() show the becouse tensorflow need to initializer function that initialize the varible.
So that below Function initialize the variable value

In [ ]:
init = tf.global_variables_initializer() # Create initializer

In [18]:
sess.run(init) # run initializer (init)

In [19]:
sess.run(var) # than again run the var session this time it's the output

4


we created variable and initialize after some time in program, it's called placeholder. In placeholder we give only data type and shape or name are optional.
In this below line we create placeholder and initialize the value after-

In [58]:
x = tf.placeholder(tf.int32,shape = None, name = "x")

In [59]:
print(x)

Tensor("x_5:0", dtype=int32)


In [60]:
print(sess.run(x, feed_dict = {x:4}))

4
